### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by stargazing-dino** [justkawal/arb_translator#3]
Hi! Friendly ping to publish new version.

If you'd like me to [help out publishing](https://dart.dev/tools/pub/cmd/pub-uploader) as well, feel free to  invite me as a collaborator for pub.dev

**Comment by justkawal** [comment]
@Nolence Sorry for delay, I'll publish it today after editing the ReadMe.

Thanks brother.

**Comment by justkawal** [comment]
@Nolence 
The new version is available at: https://pub.dev/packages/arb_translator/versions/1.0.3-null-safety
Sorry for delay, as my Mac was not starting up.

Can I know your email id of the pub.dev ?
