### ISSUE TITLE
flutter pub run arb_translator:translate not working?

### ISSUE THREAD

**Issue by stargazing-dino** [justkawal/arb_translator#4]
I don't think this is a working command. It freezes up the console for me when I try it. 

using

```
dart pub global run
```

works however. No difference in version. Curious.

p.s.

My pub.dev email is the same as my github btw, rex.magana@gmail.com

**Comment by justkawal** [comment]
@Nolence Sorry for delays, I've invited you as a publisher on pub.dev.
