### ISSUE TITLE
Apostrophes / Inverted commas being translated as &#39;

### ISSUE THREAD

**Issue by carman247** [justkawal/arb_translator#5]
When translating some languages, such as French and Welsh, translated words that would normally contain an apostrophe / inverted comma `'` are being returned with `&#39;` in their place e.g. `photo ID` becomes `photo d&#39;identité`, instead of `photo d'identité`.

It's not a major issue for me, as I can easily select all instances and replace them. It just something I thought I'd mention.

**Comment by stargazing-dino** [comment]
Odd, I specifically added `html_unescape` to handle this situation. Not sure how it's not being sanitized. Will look into this a bit later this week. Thanks for reporting !

**Comment by stargazing-dino** [comment]
Can you check this again with newest version? Here is my example usage that works

```console
dart run arb_translator:translate --source_arb ./test/resources/arb_translator_es.arb --api_key api --language_codes hi,ja
```

To make sure you have the newest version installed, run

```console
dart pub global activate arb_translator
```

sample output for me:

```arb
  "drawerTermsOfUse": "Conditions d'utilisation",
```

**Comment by justkawal** [comment]
Closing this issue, As this seems to be fruitfully handled by @Nolence .
